In [2]:
pip install tensorflow

In [3]:
# ==============================================================================
# TENSORFLOW & KERAS BASICS CRASH COURSE
# ==============================================================================

import tensorflow as tf
import numpy as np

# Silence non-critical TensorFlow info logs
import os
os.environ['TF_CPP_MIN_LOG_LEVEL'] = '2'

print(f"TensorFlow Version: {tf.__version__}")
print("-" * 50)

TensorFlow Version: 2.20.0
--------------------------------------------------


In [4]:
# ------------------------------------------------------------------------------
# 1. TENSORS & BASIC OPERATIONS
# ------------------------------------------------------------------------------
print("\n=== 1. TENSORS & OPERATIONS ===")

# Creating Tensors (Immutable multi-dimensional arrays)
t_1d = tf.constant([1.0, 2.0, 3.0])
t_2d = tf.constant([[1, 2], [3, 4]], dtype=tf.float32)

print("1D Tensor:", t_1d)
print("2D Tensor Shape:", t_2d.shape)
print("Data Type:", t_2d.dtype)

# Tensor Operations (Element-wise math)
a = tf.constant([1, 2, 3])
b = tf.constant([4, 5, 6])

print("Addition (a + b):", tf.add(a, b))
print("Multiplication (a * b):", tf.multiply(a, b))

# Converting Tensor to NumPy array
numpy_array = t_1d.numpy()
print("Converted to NumPy:", numpy_array, type(numpy_array))
print("-" * 50)


=== 1. TENSORS & OPERATIONS ===
1D Tensor: tf.Tensor([1. 2. 3.], shape=(3,), dtype=float32)
2D Tensor Shape: (2, 2)
Data Type: <dtype: 'float32'>
Addition (a + b): tf.Tensor([5 7 9], shape=(3,), dtype=int32)
Multiplication (a * b): tf.Tensor([ 4 10 18], shape=(3,), dtype=int32)
Converted to NumPy: [1. 2. 3.] <class 'numpy.ndarray'>
--------------------------------------------------


In [5]:
# ------------------------------------------------------------------------------
# 2. BUILDING A NEURAL NETWORK (tf.keras.Sequential)
# ------------------------------------------------------------------------------
print("\n=== 2. BUILDING A MODEL ===")

"""
Scenario: Predict linear equation y = 2x - 1
X inputs:  [-1,  0, 1, 2, 3, 4]
Y outputs: [-3, -1, 1, 3, 5, 7]
"""

# Prepare Training Data as NumPy float32 arrays
X_train = np.array([-1.0, 0.0, 1.0, 2.0, 3.0, 4.0], dtype=np.float32)
y_train = np.array([-3.0, -1.0, 1.0, 3.0, 5.0, 7.0], dtype=np.float32)

# Define Model Architecture
# Sequential model stacks layers linearly.
# Dense = fully connected layer with 1 unit (neuron) and input shape of 1.
model = tf.keras.Sequential([
    tf.keras.layers.Dense(units=1, input_shape=[1])
])

# Inspect Model Architecture
model.summary()
print("-" * 50)


=== 2. BUILDING A MODEL ===


/usr/local/lib/python3.12/dist-packages/keras/src/layers/core/dense.py:106: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


Model: "sequential"

┏━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━━━━━━━━━━┳━━━━━━━━━━━━━━━┓
┃ Layer (type)                    ┃ Output Shape           ┃       Param # ┃
┡━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━━━━━━━━━━╇━━━━━━━━━━━━━━━┩
│ dense (Dense)                   │ (None, 1)              │             2 │
└─────────────────────────────────┴────────────────────────┴───────────────┘

 Total params: 2 (8.00 B)

 Trainable params: 2 (8.00 B)

 Non-trainable params: 0 (0.00 B)

--------------------------------------------------


In [6]:
# ------------------------------------------------------------------------------
# 3. COMPILING & TRAINING THE MODEL
# ------------------------------------------------------------------------------
print("\n=== 3. COMPILING & TRAINING ===")

# Compile specifies how the model learns:
# - Loss Function: Measures how far off predictions are (Mean Squared Error)
# - Optimizer: Adjusts weights to minimize loss (Stochastic Gradient Descent)
model.compile(
    optimizer=tf.keras.optimizers.SGD(learning_rate=0.01),
    loss='mean_squared_error'
)

# Train the model for 300 epochs (iterations through training data)
print("Training model... Please wait a few seconds.")
history = model.fit(X_train, y_train, epochs=300, verbose=0)

print(f"Training Complete! Final Loss: {history.history['loss'][-1]:.6f}")
print("-" * 50)


=== 3. COMPILING & TRAINING ===
Training model... Please wait a few seconds.
Training Complete! Final Loss: 0.001708
--------------------------------------------------


In [7]:
# ------------------------------------------------------------------------------
# 4. PREDICTION & EVALUATION
# ------------------------------------------------------------------------------
print("\n=== 4. PREDICTION ===")

# Predict y for a new value x = 10.0 (Expected result: 2*(10) - 1 = 19.0)
x_new = np.array([[10.0]], dtype=np.float32)
prediction = model.predict(x_new, verbose=0)

print(f"Input: x = 10.0")
print(f"Predicted y value: {prediction[0][0]:.4f} (Target: ~19.0)")
print("-" * 50)


=== 4. PREDICTION ===
Input: x = 10.0
Predicted y value: 18.8794 (Target: ~19.0)
--------------------------------------------------


In [8]:
# ------------------------------------------------------------------------------
# 5. MULTI-LAYER CLASSIFICATION MODEL EXAMPLE
# ------------------------------------------------------------------------------
print("\n=== 5. MULTI-LAYER NEURAL NETWORK (Classification) ===")

# Generate dummy classification dataset (100 samples, 4 features, 2 classes)
np.random.seed(42)
X_class = np.random.randn(100, 4).astype(np.float32)
y_class = (X_class[:, 0] + X_class[:, 1] > 0).astype(np.int32) # Binary target

# Define Multi-layer Neural Network
classifier = tf.keras.Sequential([
    tf.keras.layers.Dense(8, activation='relu', input_shape=(4,)), # Hidden layer with ReLU
    tf.keras.layers.Dense(4, activation='relu'),                    # Hidden layer 2
    tf.keras.layers.Dense(1, activation='sigmoid')                  # Output layer (0 to 1 output)
])

classifier.compile(
    optimizer='adam',
    loss='binary_crossentropy',
    metrics=['accuracy']
)

# Train Classification Model
classifier.fit(X_class, y_class, epochs=20, batch_size=16, verbose=0)

# Evaluate on training data
loss, accuracy = classifier.evaluate(X_class, y_class, verbose=0)
print(f"Classifier Accuracy: {accuracy * 100:.2f}% | Loss: {loss:.4f}")
print("-" * 50)


=== 5. MULTI-LAYER NEURAL NETWORK (Classification) ===
Classifier Accuracy: 64.00% | Loss: 0.6419
--------------------------------------------------


In [9]:
# ------------------------------------------------------------------------------
# 6. SAVING & LOADING MODELS
# ------------------------------------------------------------------------------
print("\n=== 6. SAVING & LOADING MODELS ===")

# Save model to disk in native Keras format
model_filename = "my_linreg_model.keras"
model.save(model_filename)
print(f"Model saved as '{model_filename}'")

# Load model back from disk
loaded_model = tf.keras.models.load_model(model_filename)
loaded_prediction = loaded_model.predict(x_new, verbose=0)

print(f"Loaded Model Prediction for x=10.0: {loaded_prediction[0][0]:.4f}")

print("-" * 50)
print("\n=== ALL TENSORFLOW CODE EXECUTED SUCCESSFULLY! ===")


=== 6. SAVING & LOADING MODELS ===
Model saved as 'my_linreg_model.keras'
Loaded Model Prediction for x=10.0: 18.8794
--------------------------------------------------

=== ALL TENSORFLOW CODE EXECUTED SUCCESSFULLY! ===
